# Generated by Django 3.0.5 on 2020-04-14 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_logininfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='first_name',
            field=models.CharField(default=uuid.uuid1, max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='last_name',
            field=models.CharField(default=uuid.uuid1, max_length=264, unique=True),
        ),
    ]
