# Generated by Django 3.0.5 on 2020-04-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200414_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='first_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='last_name',
            field=models.CharField(max_length=264),
        ),
    ]
